# KServe deployment for Faster Whisper v2 on L40S
apiVersion: v1
kind: ConfigMap
metadata:
  name: whisper-v2-config
  namespace: default
data:
  API_KEYS: "your-production-key-1,your-production-key-2"
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: whisper-v2-l40s
  namespace: default
  annotations:
    serving.kserve.io/deploymentMode: "RawDeployment"
    serving.kserve.io/autoscalerClass: "hpa"
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 4
    containers:
    - name: whisper-server
      image: your-registry/faster-whisper-v2:gpu-l40s
      ports:
      - containerPort: 8000
        protocol: TCP
        name: http
      env:
      - name: API_KEYS
        valueFrom:
          configMapKeyRef:
            name: whisper-v2-config
            key: API_KEYS
      - name: MODEL_SIZE
        value: "large-v3"
      - name: DEVICE
        value: "cuda"
      - name: COMPUTE_TYPE
        value: "float16"
      - name: ENABLE_DIARIZATION
        value: "true"
      - name: CUDA_VISIBLE_DEVICES
        value: "0"
      resources:
        requests:
          cpu: "4"
          memory: "16Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "8"
          memory: "32Gi"
          nvidia.com/gpu: "1"
      readinessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 120
        periodSeconds: 30
        timeoutSeconds: 5
      volumeMounts:
      - name: model-cache
        mountPath: /home/whisper/.cache
      - name: nemo-cache
        mountPath: /models/nemo_cache
      - name: shm
        mountPath: /dev/shm
    volumes:
    - name: model-cache
      persistentVolumeClaim:
        claimName: whisper-model-cache-pvc
    - name: nemo-cache
      persistentVolumeClaim:
        claimName: nemo-model-cache-pvc
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi
    nodeSelector:
      nvidia.com/gpu.product: "NVIDIA-L40S"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-model-cache-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nemo-model-cache-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: Service
metadata:
  name: whisper-v2-service
  namespace: default
  labels:
    app: whisper-v2
  annotations:
    description: |
      Faster Whisper v2 API
      Models: whisper-1, whisper-1-fast, whisper-1-quality
      Features: Transcription, Translation, Speaker Diarization
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    serving.kserve.io/inferenceservice: whisper-v2-l40s
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: whisper-v2-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: whisper-v2-l40s-predictor-default
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: nvidia.com/gpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 30